<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    
  <parent>
    <groupId>com.openlandsw.rss</groupId>
    <artifactId>gatewayrss-API</artifactId>
    <version>1.0.0</version>
  </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>gateway-api</artifactId>
    <packaging>jar</packaging>
    <name>SafeCert GateWay API</name>
    <version>2.5.02</version>
    
    <dependencies>
        <dependency>
            <groupId>log4j</groupId> 
            <artifactId>log4j</artifactId> 
            <version>1.2.9</version> 
        </dependency>
	<dependency>
	        <groupId>hessian</groupId>
	        <artifactId>hessian</artifactId>
	        <version>3.2.0</version>
	</dependency>
	<dependency>
		<groupId>com.openlandsw.rss</groupId>
		<artifactId>gateway-api-comun</artifactId>
		<version>2.5.02</version>
	</dependency>
	<dependency>
		<groupId>commons-lang</groupId>
		<artifactId>commons-lang</artifactId>
		<version>2.6</version>
	</dependency>
    <dependency>
    	<groupId>bouncy-castle</groupId>
        <artifactId>bcprov-jdk15</artifactId>
        <scope>provided</scope>
        <version>1.38</version>
	</dependency>
    <dependency>
    	<groupId>bouncy-castle</groupId>
        <artifactId>bcmail-jdk15</artifactId>
        <scope>provided</scope>
        <version>1.38</version>
	</dependency>	
    </dependencies>
    
    <build>
	    <plugins>
		    <plugin>
		      	<!-- Configuramos este proyecto para que pueda utilizar funcionalidad de Java 5 -->
		        <artifactId>maven-compiler-plugin</artifactId>
		        <configuration>
		          <source>1.5</source>
		          <target>1.5</target>
		        </configuration>
		    </plugin>
	    </plugins>
    </build>
    
    	<profiles>
        <profile>
        <id>release</id>
        <build>
            <plugins>
				<plugin>
		        	<groupId>org.apache.maven.plugins</groupId>
		        	<artifactId>maven-dependency-plugin</artifactId>
		        	<version>2.6</version>
		        	<executions>
		          		<execution>
		            		<id>copy</id>
		            		<phase>install</phase>
		            		<goals>
		              			<goal>copy</goal>
		            		</goals>
		            		<configuration>
		              			<artifactItems>
			                		<artifactItem>
			                  			<groupId>com.openlandsw.rss</groupId>
			                  			<artifactId>gateway-api-comun</artifactId>
			                  			<version>${project.version}</version>
			                  			<type>jar</type>
			                  			<overWrite>false</overWrite>
			                		</artifactItem>
			                		<artifactItem>
			                  			<groupId>log4j</groupId>
			                  			<artifactId>log4j</artifactId>
			                  			<version>1.2.14</version>
			                  			<type>jar</type>
			                  			<overWrite>false</overWrite>
			                		</artifactItem>
			                		<artifactItem>
			                  			<groupId>hessian</groupId>
			                  			<artifactId>hessian</artifactId>
			                  			<version>3.2.0</version>
			                  			<type>jar</type>
			                  			<overWrite>false</overWrite>
			                		</artifactItem>
			                		<artifactItem>
			                  			<groupId>commons-lang</groupId>
										<artifactId>commons-lang</artifactId>
										<version>2.6</version>
			                  			<type>jar</type>
			                  			<overWrite>false</overWrite>
			                		</artifactItem>
		              			</artifactItems>
		              			<outputDirectory>${path.release}/safecert-gateway/API</outputDirectory>
		            		</configuration>
		          		</execution>
		        	</executions>
				</plugin>
				<plugin>
			        <groupId>org.apache.maven.plugins</groupId>
			        <artifactId>maven-javadoc-plugin</artifactId>
			        <version>2.10.4</version>
			        <executions>
			            <execution>
			                <id>attach-javadocs</id>
			                <phase>install</phase>
			                <goals>
			                    <goal>test-javadoc-no-fork</goal>
			                </goals>
			                <configuration>
			                    <additionalparam>${javadoc.opts}</additionalparam>
			                    <reportOutputDirectory>${path.release}/test-API/${project.artifactId}</reportOutputDirectory>
			                    <detectOfflineLinks>false</detectOfflineLinks>
			                </configuration>
			            </execution>
			        </executions>
			    </plugin>
			    <plugin>
			        <groupId>org.apache.maven.plugins</groupId>
			        <artifactId>maven-site-plugin</artifactId>
			        <version>3.3</version>
			        <configuration>
			          <reportPlugins>
			            <plugin>
			              <groupId>org.apache.maven.plugins</groupId>
			              <artifactId>maven-javadoc-plugin</artifactId>
			              <configuration>
			              	<additionalparam>${javadoc.opts}</additionalparam>
			              </configuration>
			            </plugin>
			          </reportPlugins>
			        </configuration>
				</plugin>
            </plugins>
        </build>
		</profile>
	</profiles>
    
</project>
