#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Dec 20 11:56:57 CET 2024
maven-metadata-thirdparty-releases.xml.error=
maven-metadata-github-governib-maven-repos.xml.lastUpdated=1734692184168
maven-metadata-github_governib_maven.xml.lastUpdated=1734692183272
maven-metadata-github_governib_maven.xml.error=
maven-metadata-thirdparty-releases.xml.lastUpdated=1734692217713
maven-metadata-github-governib-maven-repos.xml.error=
