#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Dec 11 08:05:42 CET 2024
maven-metadata-github_governib_maven_repos.xml.lastUpdated=1733899935971
maven-metadata-github-governib-maven-repos.xml.lastUpdated=1733899673511
maven-metadata-github-governib-maven.xml.lastUpdated=1733899672255
maven-metadata-Viavansi.xml.error=
maven-metadata-Viavansi.xml.lastUpdated=1733900742405
maven-metadata-github_governib_maven.xml.lastUpdated=1733899679957
maven-metadata-github_governib_maven.xml.error=
maven-metadata-github_governib_maven_repos.xml.error=
maven-metadata-github-governib-maven-repos.xml.error=
maven-metadata-github-governib-maven.xml.error=
